[dockerhosts]
docker01 ansible_host=VERVANG_DOOR_IP_VAN_VM

[dockerhosts:vars]
ansible_user=deploy
ansible_ssh_private_key_file=~/.ssh/id_azure

[vpn]
vpn-router ansible_host=52.157.87.21 ansible_user=deploy ansible_ssh_private_key_file=~/.ssh/id_azure
